# Default values for the parameters of the simulation.
map_size: 2000 # Given in meters
stop_time: 480 # Given in minutes. 480 = 8 hours (default value)
fire_rates: 
  # Given in aimed shots per minute.
  blue_min: 1
  blue_max: 25
  red_min: 1
  red_max: 25

terrain_library:
  # Type: (movement cost, probability)
  # Probability should sum to 1.0 across all terrain types.
  # Movement cost is calibrated to the Pandolf-Santee model and should not be changed.
  light_brush: [1.2, 0.50]
  heavy_brush: [1.5, 0.20]
  packed_dirt: [1.1, 0.15]
  loose_sand: [2.1, 0.10]
  paved: [1.0, 0.05]

threat_library:
  # Format: [a, b, c] 
  # contstants a projectile velocity function: v(x) = ax^2 + bx + c 
  # where x is the distance in meters between the shooter and target.
  Garnet: [0.0011, -2.9354, 2844.8]
  Amethyst: [0.0017, -4.2007, 3167.4]
  Aquamarine: [0.001, -2.8943, 2836.6]
  Diamond: [0.0007, -2.4645, 2777.8]
  Emerald: [0.001, -2.8219, 2765.7]
  Pearl: [0.0009, -2.524, 2746.6]
  Ruby: [0.0009, -2.5037, 2745.5]
  Peridot: [0.0026, -4.0108, 2356.4]
  Sapphire: [0.0018, -3.6389, 2334.7]
  Opal: [0.0016, -4.1357, 3163.8]
  Topaz: [0.0015, -4.0872, 3160.6]
  Zircon: [0.0007, -2.4835, 2782.8]

armor_profiles:
  # Mass is given in kg.
  # Threats are given in the form of [a, b] which are parameters of a beta distribution that 
  # determines the probability of the given threat penetrating the armor. 
  # p(v) = exp(a + bv) where v is the velocity of the projectile in m/s.
  Basilone Ballistic Insert:
    Mass: 8.3043963255
    Garnet: [-15, 0.004]
    Amethyst: [-17, 0.004]
    Aquamarine: [-14, 0.004]
    Diamond: [-15, 0.004]
    Emerald: [-12, 0.004]
    Pearl: [-25, 0.004]
    Ruby: [-25, 0.004]
    Peridot: [-14, 0.004]
    Sapphire: [-25, 0.004]
    Opal: [-25, 0.004]
    Topaz: [-20, 0.004]
    Zircon: [-8, 0.004]
  Chesty Ballistic Insert:
    Mass: 6.35042018586
    Garnet: [-14, 0.004]
    Amethyst: [-10, 0.004]
    Aquamarine: [-8, 0.004]
    Diamond: [-13, 0.004]
    Emerald: [-4, 0.004]
    Pearl: [-25, 0.004]
    Ruby: [-25, 0.004]
    Peridot: [-13, 0.004]
    Sapphire: [-25, 0.004]
    Opal: [-25, 0.004]
    Topaz: [-16, 0.004]
    Zircon: [-2, 0.004]
  Hathcock Ballistic Insert:
    Mass: 4.39644405
    Garnet: [-6, 0.004]
    Amethyst: [-4, 0.004]
    Aquamarine: [-2, 0.004]
    Diamond: [-5, 0.004]
    Emerald: [-1, 0.004]
    Pearl: [-14, 0.004]
    Ruby: [-20, 0.004]
    Peridot: [-8, 0.004]
    Sapphire: [-10, 0.004]
    Opal: [-18, 0.004]
    Topaz: [-11, 0.004]
    Zircon: [-1, 0.004]

threat_probs:
  # These are the probabilities of each threat being present in a given scenario.
  # Scenarios are orderd in acending challenge level.
  Krulak’s Three Block War:
    Garnet: 0.01
    Amethyst: 0
    Aquamarine: 0
    Diamond: 0.04
    Emerald: 0
    Pearl: 0.45
    Ruby: 0.15
    Peridot: 0.15
    Sapphire: 0.15
    Opal: 0.05
    Topaz: 0
    Zircon: 0
  Pershing’s Ghost:
    Garnet: 0.10
    Amethyst: 0.02
    Aquamarine: 0.01
    Diamond: 0.10
    Emerald: 0
    Pearl: 0.20
    Ruby: 0.05
    Peridot: 0.25
    Sapphire: 0.15
    Opal: 0.08
    Topaz: 0.04
    Zircon: 0
  Nightmare from Mattis Street:
    Garnet: 0.34
    Amethyst: 0.11
    Aquamarine: 0.09
    Diamond: 0.10
    Emerald: 0.04
    Pearl: 0.05
    Ruby: 0.05
    Peridot: 0.05
    Sapphire: 0.01
    Opal: 0.05
    Topaz: 0.10
    Zircon: 0.01